# if test -n "$IN_NIX_SHELL"; then return; fi

#if [ -z "$__NIX_DARWIN_SET_ENVIRONMENT_DONE" ]; then
  #. /nix/store/nwbz1bg76b0gmblw0n1y1s3r53kpsslh-set-environment
#fi
fish_add_path /run/current-system/sw/bin
fish_add_path /opt/homebrew/bin

export EDITOR="vi"

fish_vi_key_bindings
set -U fish_greeting

eval "$(starship init fish)"
