name: "Cachix"

on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  builds:
    name: Build configuration
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6.0.1
      with:
        fetch-depth: 0 # Nix Flakes doesn't work on shallow clones
    - uses: cachix/install-nix-action@v31.9.0
      with:
        extra_nix_config: |
          experimental-features = nix-command flakes
    - uses: cachix/cachix-action@v16
      with:
        name: jrestivo
        signingKey: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix build .#nixosConfigurations.laptop.config.system.build.toplevel -L
